import { FullResult } from "@/hooks/useSimulator";
import { formatINR } from "@/lib/formatters";

export function generateCSV(result: FullResult): string {
  const lines: string[] = [];
  
  // Header info
  lines.push(`Scenario,${result.scenarioName}`);
  lines.push(`Crop,${result.cropName}`);
  lines.push(`Cycle Days,${result.sim.cycle_days}`);
  lines.push(`Yield (kg),${result.sim.yield_kg}`);
  lines.push(`Success Probability,${(result.sim.success_probability * 100).toFixed(1)}%`);
  lines.push(`Revenue (INR),${result.economics.revenue}`);
  lines.push(`Total Cost (INR),${result.economics.total_cost}`);
  lines.push(`Net Profit (INR),${result.economics.net_profit}`);
  lines.push(`ROI,${result.economics.roi.toFixed(2)}%`);
  lines.push("");
  lines.push("Day,Biomass Per Plant (g),Biomass Total (kg),Stress Factor,Growth Stage");
  
  for (const s of result.sim.daily_states) {
    lines.push(`${s.day},${s.biomass_per_plant_g},${s.biomass_total_kg},${s.stress_factor},${s.growth_stage}`);
  }
  
  return lines.join("\n");
}

export function downloadCSV(result: FullResult) {
  const csv = generateCSV(result);
  const blob = new Blob([csv], { type: "text/csv" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `aerofarm_${result.cropKey}_${Date.now()}.csv`;
  a.click();
  URL.revokeObjectURL(url);
}

export function emailReport(result: FullResult) {
  const subject = encodeURIComponent(`AeroFarm Report: ${result.scenarioName}`);
  const body = encodeURIComponent(
    `AeroFarm Simulation Report\n` +
    `========================\n\n` +
    `Scenario: ${result.scenarioName}\n` +
    `Crop: ${result.cropName}\n` +
    `Cycle: ${result.sim.cycle_days} days\n` +
    `Yield: ${result.sim.yield_kg} kg\n` +
    `Success: ${(result.sim.success_probability * 100).toFixed(1)}%\n\n` +
    `Revenue: ${formatINR(result.economics.revenue)}\n` +
    `Total Cost: ${formatINR(result.economics.total_cost)}\n` +
    `Net Profit: ${formatINR(result.economics.net_profit)}\n` +
    `ROI: ${result.economics.roi.toFixed(2)}%\n` +
    `Payback: ${result.economics.payback_period_years > 0 ? result.economics.payback_period_years.toFixed(1) + " years" : "N/A"}\n\n` +
    `Generated by AeroFarm Simulator`
  );
  window.open(`mailto:?subject=${subject}&body=${body}`);
}
